FROM python:3.7-stretch

RUN apt-get update && apt-get install -y \
  supervisor \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN pip install --upgrade pip

COPY docker/pip.conf /etc/
COPY docker/entrypoint.sh /
COPY docker/supervisor/rest.conf /etc/supervisor/conf.d
COPY src /src
RUN cd /src && pip3 install -U --upgrade-strategy=eager --trusted-host pypi.econo.unlp.edu.ar --upgrade -e .

#hago deploy de la librería para que los demas sistemas la puedan usar
#COPY docker/.pypirc /root/
#RUN cd /src && python setup.py sdist upload -r internal

WORKDIR /src

EXPOSE 10502
ENTRYPOINT ["/entrypoint.sh"]
